export interface Chapter {
  id: number
  title: string
  content: string[]
}

export const chapters: Chapter[] = [
  {
    id: 1,
    title: 'California Traffic Laws',
    content: [
      'California traffic laws are established under the California Vehicle Code (CVC), which governs all aspects of vehicle operation on public roads. Understanding these laws is essential for safe and legal driving.',
      'The right-of-way rules in California determine which driver has the legal right to proceed first at intersections, crosswalks, and merges. These rules exist to prevent collisions and ensure orderly traffic flow.',
      'At uncontrolled intersections (no signs or signals), the driver who arrives first has the right of way. When two vehicles arrive simultaneously, the driver on the left must yield to the driver on the right.',
      'California Vehicle Code Section 21950 requires drivers to yield the right-of-way to any pedestrian crossing in a marked or unmarked crosswalk. This law has no exceptions.',
      'Speed limits in California are the maximum safe speed under ideal conditions. The Basic Speed Law (CVC 22350) states you must never drive faster than is safe for current conditions, regardless of the posted limit.',
      'School zones have a 25 mph speed limit when children are present. Work zones often have reduced speed limits, and fines are doubled in active work zones.',
      'California has a hands-free law requiring drivers to use a mounted device operated by a single touch. Drivers under 18 may not use any wireless device while driving.',
      'Running a red light is one of the most dangerous traffic violations. California law requires drivers to stop before the limit line, crosswalk, or intersection when the signal is red.',
      'Seat belts are required for all occupants in California. Children under 8 must be secured in a car seat or booster seat in the back seat.',
      'DUI laws in California set the legal BAC limit at 0.08% for adults, 0.04% for commercial drivers, and 0.01% for drivers under 21. First-offense DUI penalties include fines, license suspension, and possible jail time.',
    ],
  },
  {
    id: 2,
    title: 'Defensive Driving',
    content: [
      'Defensive driving is a set of skills that allows you to defend yourself against possible collisions caused by bad drivers, drunk drivers, and poor weather. It goes beyond simply knowing traffic laws.',
      'The Smith System is a defensive driving framework with five principles: Aim High in Steering, Get the Big Picture, Keep Your Eyes Moving, Leave Yourself an Out, and Make Sure They See You.',
      'Aim High in Steering means looking 15 seconds ahead in city driving and 20–30 seconds ahead on the highway. This allows you to anticipate problems and adjust early rather than react suddenly.',
      'The three-second following distance rule is the minimum safe following distance in ideal conditions. Choose a fixed object ahead, and when the vehicle in front passes it, count three seconds before you reach the same point.',
      'In rain, fog, or heavy traffic, extend your following distance to five or six seconds. At highway speeds in rain, your stopping distance increases dramatically.',
      'Covering the brake — moving your foot from the accelerator to hover over the brake — at intersections and in high-risk situations reduces your reaction time significantly.',
      'Scanning intersections independently of traffic signals is critical. Always look left, right, and left again before entering any intersection, even on a green light.',
      'Space management means maintaining buffers in all directions: front, rear, left, right, above, and below. Most drivers only manage their front space.',
      'If your brakes fail, pump the pedal rapidly, downshift, and use the parking brake gently. If a tire blows out, do not brake hard — grip the wheel, maintain heading, and ease off the gas.',
      'Night driving requires reduced speed, proper headlight use, and extra alertness. Your headlights illuminate only 350 feet ahead, but at 65 mph your stopping distance is over 500 feet.',
    ],
  },
  {
    id: 3,
    title: 'Alcohol, Drugs, and Driving',
    content: [
      'Alcohol is the leading drug involved in fatal crashes. It impairs judgment, reaction time, coordination, and vision — all critical driving functions — often before the driver feels impaired.',
      'The legal BAC limit in California is 0.08% for adult drivers. However, impairment begins at the first drink. Even at 0.02% BAC, drivers show reduced ability to track moving objects.',
      'At 0.05% BAC, coordination is reduced and steering becomes more difficult. At 0.08%, reaction time, concentration, and short-term memory are significantly impaired.',
      'Alcohol is absorbed into the bloodstream through the stomach and small intestine. Food slows absorption but does not prevent impairment. Only time eliminates alcohol from your system.',
      'Coffee, cold showers, and exercise do not sober you up. The liver processes alcohol at a fixed rate of approximately one standard drink per hour.',
      'Marijuana impairs driving even when consumed legally for medical or recreational purposes. It slows reaction time, impairs lane tracking, and reduces coordination.',
      'Prescription medications including antihistamines, sleep aids, anxiety medications, and some painkillers can impair driving. Always read warnings and consult your doctor.',
      'Drugged driving (DUID) carries the same penalties as alcohol DUI in California. Law enforcement uses drug recognition experts and chemical testing to identify drug impairment.',
      'If you are planning to drink, plan your transportation before your first drink. Use a designated driver, rideshare service, or taxi. Arrange a safe way home when you are sober.',
      'California has an implied consent law: by driving on California roads, you consent to chemical testing if arrested for DUI. Refusing a test results in automatic license suspension.',
    ],
  },
  {
    id: 4,
    title: 'Distracted Driving',
    content: [
      'Distracted driving is any activity that diverts your attention from driving. There are three types: visual (eyes off road), manual (hands off wheel), and cognitive (mind off driving).',
      'Texting while driving is the most dangerous distraction because it combines all three types simultaneously. Sending a text takes your eyes off the road for an average of 5 seconds.',
      'At 55 mph, 5 seconds of inattention means you have traveled the length of a football field — 300 feet — with your eyes closed and no ability to react to hazards.',
      'California Vehicle Code 23123 prohibits handheld cell phone use while driving. Adults may use hands-free devices; drivers under 18 may not use any wireless device.',
      'Hands-free calls still cause cognitive distraction. Research shows that hands-free calls impair driving for up to 27 seconds after the call ends, even with eyes on the road.',
      'Eating while driving increases crash risk by approximately 80%. Foods requiring two hands, dripping, or unwrapping while driving are particularly dangerous.',
      'In-vehicle infotainment systems — navigation, music controls, and voice commands — can create significant cognitive distraction even when not requiring hand or eye movement.',
      'Passenger conversations are generally less distracting than phone calls because passengers are aware of driving conditions and naturally pause during complex driving situations.',
      'Drowsiness is a form of cognitive impairment comparable to intoxication. Driving after 20 hours without sleep impairs you similarly to a 0.08% BAC.',
      'If you feel drowsy while driving, pull over safely and rest. Rolling down the window, turning up the music, or drinking coffee provides only a few minutes of temporary alertness.',
    ],
  },
  {
    id: 5,
    title: 'Sharing the Road',
    content: [
      'California roads are shared by vehicles, motorcycles, bicycles, pedestrians, and large trucks. Understanding the needs and limitations of each road user improves safety for everyone.',
      'Motorcycles are entitled to the full use of their lane. Never share a lane with a motorcycle. When following a motorcycle, maintain a four-second following distance — motorcycles can stop faster than cars.',
      'Check your blind spots before changing lanes or turning — motorcycles can be hidden in areas your mirrors do not cover. Many motorcycle crashes occur when car drivers fail to see approaching motorcycles.',
      'Lane splitting — riding a motorcycle between lanes of slow or stopped traffic — is legal in California. Be aware that motorcycles may be moving between lanes in heavy traffic.',
      'Bicyclists have the same rights and responsibilities as vehicle drivers. They may use the full lane when necessary for safety. Pass a cyclist with a minimum of three feet of clearance.',
      'Dooring — opening your car door into a cyclist — is illegal under CVC 22517. Use the Dutch Reach: open your door with your far hand, which naturally rotates your body to check for approaching cyclists.',
      'Large trucks have significant blind spots on all four sides. If you cannot see the truck driver in their mirror, they cannot see you. Avoid driving in these blind zones.',
      'Trucks need up to 40% more stopping distance than cars. Never cut in front of a truck and then brake suddenly. Merge well ahead of the truck before slowing.',
      'School buses with flashing red lights must be stopped for in both directions on undivided roads. On divided highways, only traffic behind the bus must stop.',
      'Emergency vehicles with lights and sirens require you to pull to the right and stop until they have passed. Never follow an emergency vehicle more closely than 300 feet.',
    ],
  },
  {
    id: 6,
    title: 'Vehicle Safety',
    content: [
      'Vehicle maintenance directly affects your safety and legal compliance on California roads. A poorly maintained vehicle is both more dangerous and more likely to result in citations.',
      'Tires are your only contact with the road. Check tire pressure monthly — underinflated tires reduce fuel efficiency, handling, and increase blowout risk. Proper pressure is listed on the door jamb sticker.',
      'Tire tread depth must be at least 2/32 of an inch. Use the penny test: insert a penny into the tread with Lincoln\'s head down — if you can see his entire head, replace the tire.',
      'Brakes should be inspected at least once a year. Signs of brake wear include squealing or grinding sounds, longer stopping distances, vibration when braking, or the vehicle pulling to one side.',
      'Headlights must be on from 30 minutes after sunset to 30 minutes before sunrise, and whenever visibility is less than 1,000 feet. In California, wipers on means headlights on.',
      'Anti-lock braking systems (ABS) prevent wheel lockup during hard braking, allowing you to maintain steering control. With ABS, apply firm steady pressure — do not pump the brakes.',
      'Electronic Stability Control (ESC) detects skids and automatically applies individual wheel brakes to restore stability. All vehicles since 2012 are required to have ESC.',
      'Airbags supplement seat belts — they do not replace them. Never disable airbags. Children under 12 should ride in the back seat, away from front airbags.',
      'A red oil pressure light means stop immediately — continuing to drive will destroy your engine within minutes. A red engine temperature light also means stop driving.',
      'Keep your registration current and carry proof of insurance at all times. California requires minimum liability coverage of 15/30/5 — though higher limits are strongly recommended.',
    ],
  },
  {
    id: 7,
    title: 'Environmental Conditions',
    content: [
      'California\'s varied geography creates a wide range of driving conditions — from coastal fog to mountain snow to desert heat. Adjusting your driving for conditions is both a legal and safety requirement.',
      'Rain significantly reduces traction, visibility, and stopping ability. The first 10–15 minutes of rain are the most dangerous as oils rise to the surface before being washed away.',
      'Hydroplaning occurs when your tires lose contact with the road surface and ride on a film of water. It can happen at speeds as low as 35 mph on worn tires. To recover, ease off the gas — do not brake hard.',
      'Tule fog is a ground-level fog that forms in California\'s Central Valley, primarily from November through March. It can reduce visibility to near zero within minutes and is responsible for some of California\'s deadliest crashes.',
      'In fog, use low-beam headlights — high beams reflect off fog and reduce visibility further. If visibility drops to near zero, pull completely off the road, turn off your lights, and wait.',
      'Mountain driving requires lower gear for both ascending and descending steep grades. Engine braking on descents prevents brake overheating. Carry tire chains when required.',
      'Heat affects tires: a tire already at proper pressure will increase in pressure as temperature rises. In extreme heat, avoid overinflation and check tires before long trips.',
      'Nighttime desert driving presents risks from wildlife, fatigue from long straight roads, and cold temperatures. Watch for animals crossing — they are most active at dawn and dusk.',
      'Wildfire smoke reduces visibility and air quality. If smoke is heavy, treat it like fog — reduce speed, use headlights, and increase following distance.',
      'Wind, particularly in coastal, desert, and mountain pass areas, can dramatically affect vehicle handling. Crosswinds affect high-profile vehicles, tow vehicles, and motorcycles most severely.',
    ],
  },
  {
    id: 8,
    title: 'Road Rage and Aggressive Driving',
    content: [
      'Road rage is a serious and growing problem on California roads. Aggressive driving behaviors escalate to road rage when they become personal — directed at a specific driver with intent to threaten or harm.',
      'Aggressive driving includes speeding, tailgating, cutting off other vehicles, failing to yield, weaving through traffic, and running red lights. These behaviors increase crash risk for everyone.',
      'Road rage escalates aggressive driving into criminal behavior: threatening gestures, verbal confrontations, ramming another vehicle, or displaying or using a weapon.',
      'Common road rage triggers include heavy traffic, running late, being cut off, tailgating by other drivers, and accumulated daily stress that carries into driving.',
      'If another driver behaves aggressively toward you, do not engage. Avoid eye contact, do not gesture or honk, and create distance. Do not block the driver or prevent them from passing.',
      'If you feel threatened by another driver, do not go home. Drive to a public place, a police station, or call 911. Do not exit your vehicle to confront another driver.',
      'Managing your own driving anger starts before you get in the car. Leave early enough that you are not rushed. Reframe other drivers\' behavior as mistakes rather than personal affronts.',
      'Road rage carries serious legal consequences including criminal assault charges, license revocation, civil liability for damages and injuries, and increased insurance rates.',
      'Driving while emotionally distressed — angry, grieving, or anxious — is a form of cognitive impairment. If you are too upset to focus, wait before driving.',
      'California\'s Vision Zero initiative aims to eliminate all traffic fatalities. Road rage deaths are preventable. The choice to disengage from aggressive encounters is always the right one.',
    ],
  },
  {
    id: 9,
    title: 'Pedestrian and Cyclist Safety',
    content: [
      'Pedestrians and cyclists are the most vulnerable road users in California. A collision between a vehicle and a person on foot or on a bicycle is almost always catastrophic for the person outside the vehicle.',
      'A vehicle traveling at 30 mph carries approximately 250,000 foot-pounds of kinetic energy. A pedestrian carries almost none. At 30 mph, pedestrian fatality risk is approximately 45%.',
      'California Vehicle Code Section 21950 requires drivers to yield the right-of-way to any pedestrian crossing in a marked or unmarked crosswalk — with no exceptions.',
      'When stopping for a pedestrian, stop before the limit line. Do not proceed until the pedestrian has completely cleared your lane — not just reached the center line.',
      'Never pass a vehicle stopped at a crosswalk. A pedestrian may be crossing in front of the stopped vehicle, hidden from your view.',
      'Blind pedestrians using a white cane or guide dog have absolute right-of-way. You must stop and remain stopped until the cane or dog is completely clear of your path.',
      'The most common pedestrian collision type occurs when a driver turning right or left strikes a pedestrian crossing with the walk signal. Yielding to pedestrians is required even when you have a green light.',
      'Cyclists have the same rights and responsibilities as vehicle drivers. They may use the full lane when necessary. Pass with at least three feet of clearance at all times.',
      'After passing a cyclist, do not immediately merge back into the bike lane or cut across their path. Signal and complete the pass only when there is sufficient clearance ahead.',
      'Use the Dutch Reach to open your car door: reach across with your far hand, which rotates your body so you are naturally looking back for approaching cyclists before the door opens.',
    ],
  },
  {
    id: 10,
    title: 'Traffic Violations and Consequences',
    content: [
      'California\'s traffic violation system is designed to promote safe driving through financial penalties, license point accumulation, and in serious cases, criminal prosecution.',
      'Traffic citations in California are classified as infractions, misdemeanors, or felonies. Most moving violations are infractions. DUI and reckless driving are misdemeanors or felonies.',
      'The DMV point system adds points to your driving record for moving violations. One point is assessed for most infractions; two points for serious violations like DUI or reckless driving.',
      'Under California\'s Negligent Operator Treatment System (NOTS), accumulating 4 points in 12 months, 6 in 24 months, or 8 in 36 months results in license suspension.',
      'Traffic school (Traffic Violator School) allows eligible drivers to mask a point from their driving record. Eligibility requires a valid license, the violation must be a one-point infraction, and you must not have attended TVS in the past 18 months.',
      'Completing a TVS course does not remove the violation from your DMV record — it masks the point so insurance companies cannot see it at renewal.',
      'The certificate of completion from this course must be submitted to your court before your court deadline. Missing this deadline forfeits your traffic school credit.',
      'Failure to appear on a traffic citation results in additional fines, a hold on your license, and potentially a warrant for your arrest.',
      'Red light cameras photograph vehicles entering intersections against a red signal and mail citations to the registered owner. Only the driver can be convicted — not automatically the vehicle owner.',
      'Your driving record follows you for years. Multiple violations increase your insurance rates significantly. Safe driving is not just a legal obligation — it is the most effective way to protect your financial wellbeing as a driver.',
    ],
  },
]

export const PASSING_SCORE = 70 // 70% to pass

export interface Question {
  id: number
  question: string
  options: string[]
  correct: number
  chapter: number
}

export const examQuestions: Question[] = [
  {
    id: 1,
    question: 'At an uncontrolled intersection where two vehicles arrive at the same time, who has the right of way?',
    options: ['The driver going straight', 'The driver on the left', 'The driver on the right', 'The larger vehicle'],
    correct: 2,
    chapter: 1,
  },
  {
    id: 2,
    question: 'What does the Basic Speed Law (CVC 22350) require?',
    options: [
      'Always drive at the posted speed limit',
      'Never drive faster than is safe for current conditions',
      'Drive at least 45 mph on freeways',
      'Slow to 15 mph in school zones',
    ],
    correct: 1,
    chapter: 1,
  },
  {
    id: 3,
    question: 'Under California law, what must you do when a pedestrian is in a crosswalk?',
    options: [
      'Yield only if the pedestrian has a walk signal',
      'Slow down but do not need to stop',
      'Yield the right-of-way without exception',
      'Honk to alert the pedestrian',
    ],
    correct: 2,
    chapter: 1,
  },
  {
    id: 4,
    question: 'The Smith System principle "Aim High in Steering" means:',
    options: [
      'Keep your steering wheel held high',
      'Look 15–20 seconds ahead to anticipate problems',
      'Aim for the highest speed safely possible',
      'Keep your eyes above the horizon',
    ],
    correct: 1,
    chapter: 2,
  },
  {
    id: 5,
    question: 'What is the minimum following distance under ideal conditions?',
    options: ['1 second', '2 seconds', '3 seconds', '5 seconds'],
    correct: 2,
    chapter: 2,
  },
  {
    id: 6,
    question: 'At what BAC level does California law consider adult drivers to be legally impaired?',
    options: ['0.04%', '0.06%', '0.08%', '0.10%'],
    correct: 2,
    chapter: 3,
  },
  {
    id: 7,
    question: 'Which of the following will NOT help sober you up faster?',
    options: ['Drinking coffee', 'Taking a cold shower', 'Eating food', 'All of the above — only time eliminates alcohol'],
    correct: 3,
    chapter: 3,
  },
  {
    id: 8,
    question: 'How long does it take for eyes to leave the road when sending a text message?',
    options: ['1 second', '3 seconds', '5 seconds', '10 seconds'],
    correct: 2,
    chapter: 4,
  },
  {
    id: 9,
    question: 'California\'s hands-free law allows drivers under 18 to:',
    options: [
      'Use a hands-free device only',
      'Use a mounted phone with one touch',
      'Make emergency calls only',
      'Use no wireless device at all while driving',
    ],
    correct: 3,
    chapter: 4,
  },
  {
    id: 10,
    question: 'What is the minimum clearance required when passing a bicyclist in California?',
    options: ['1 foot', '2 feet', '3 feet', '4 feet'],
    correct: 2,
    chapter: 5,
  },
  {
    id: 11,
    question: 'When must you stop for a school bus?',
    options: [
      'Only when driving behind the bus',
      'In both directions on undivided roads when red lights are flashing',
      'Only in school zones',
      'When children are visible near the bus',
    ],
    correct: 1,
    chapter: 5,
  },
  {
    id: 12,
    question: 'What does the penny test determine about your tires?',
    options: ['Tire pressure', 'Tread depth', 'Tire age', 'Alignment'],
    correct: 1,
    chapter: 6,
  },
  {
    id: 13,
    question: 'With anti-lock brakes (ABS), what is the correct technique during emergency braking?',
    options: [
      'Pump the brakes rapidly',
      'Apply firm, steady pressure and do not pump',
      'Press the brake halfway and hold',
      'Press and release every two seconds',
    ],
    correct: 1,
    chapter: 6,
  },
  {
    id: 14,
    question: 'During rain, when is road surface traction most reduced?',
    options: [
      'After 30 minutes of heavy rain',
      'During the first 10–15 minutes when oils rise to the surface',
      'Only during thunderstorms',
      'At night during rain',
    ],
    correct: 1,
    chapter: 7,
  },
  {
    id: 15,
    question: 'In heavy fog, you should use:',
    options: ['High-beam headlights', 'Low-beam headlights', 'Hazard lights only', 'No lights — they reduce visibility'],
    correct: 1,
    chapter: 7,
  },
  {
    id: 16,
    question: 'If an aggressive driver is following you, you should:',
    options: [
      'Speed up to create distance',
      'Stop and confront the driver',
      'Drive to a public place or police station',
      'Block the driver from passing',
    ],
    correct: 2,
    chapter: 8,
  },
  {
    id: 17,
    question: 'At what speed does pedestrian fatality risk reach approximately 45%?',
    options: ['20 mph', '30 mph', '40 mph', '50 mph'],
    correct: 1,
    chapter: 9,
  },
  {
    id: 18,
    question: 'What is the Dutch Reach?',
    options: [
      'A technique for parallel parking',
      'Opening your car door with your far hand to check for cyclists',
      'A method for checking blind spots before lane changes',
      'A hand signal for turning',
    ],
    correct: 1,
    chapter: 9,
  },
  {
    id: 19,
    question: 'Under California\'s NOTS system, license suspension occurs after how many points in 12 months?',
    options: ['2 points', '3 points', '4 points', '6 points'],
    correct: 2,
    chapter: 10,
  },
  {
    id: 20,
    question: 'Traffic school completion masks a point violation by:',
    options: [
      'Permanently removing it from your DMV record',
      'Preventing it from appearing on your public driving record for insurance purposes',
      'Reducing the fine by 50%',
      'Allowing you to attend traffic school again immediately',
    ],
    correct: 1,
    chapter: 10,
  },
]
